repositorio/raiz/apps/usuarios/urls.py
from django.urls import path, reverse_lazy
from . import views

from django.contrib.auth import views as auth

app_name= 'usuarios'


urlpatterns = [
    
    path('registrarse/',views.registrarse.as_view(), name='registrarse'),
    path('login/',auth.LoginView.as_view(template_name='usuarios/loguearse.html'),name='loguearse'), #en vez de pasarle una vista mia paso una de django
    path('logout/',auth.LogoutView.as_view(),name="logout"),
    path('listar/',views.listarUsuarios,name="listarUsuarios"),
    path('eliminar/<int:pk>',views.eliminarUsuario,name="eliminarUsuario"),    
    path('modificar/<int:pk>',views.modificarUsuario,name="modificarUsuario"),   
    
    #modificar Password
    path('password_change/', views.password_change.as_view(), name='password_change'),
    path('password_success/', views.password_success, name='password_success'),
    #recuperacion de Password
    path(
        'password_reset/',
        auth.PasswordResetView.as_view(
        template_name='usuarios/reestablecerPassword/password_reset_form.html',
        email_template_name='usuarios/reestablecerPassword/password_reset_email.html',
        success_url=reverse_lazy('usuarios:password_reset_done')),
        name='password_reset'),
    path(
        'password_reset_done/',
        auth.PasswordResetDoneView.as_view(
        template_name='usuarios/reestablecerPassword/password_reset_done.html'),
        name='password_reset_done'),

    path(
        'password_reset/<uidb64>/<token>',
        auth.PasswordResetConfirmView.as_view(
        template_name='usuarios/reestablecerPassword/password_reset_confirm.html',
        success_url=reverse_lazy('usuarios:password_reset_complete')),
        name='password_reset_confirm'),

    path('password_reset_complete/',
        views.CustomPasswordResetCompleteView.as_view(
        template_name='usuarios/reestablecerPassword/password_reset_complete.html'),
        name='password_reset_complete'),                                
]

repositorio/raiz/blog/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings


from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', views.Home, name = 'home'),
    path('contacto/', views.Contacto, name = 'contacto'),
    path('usuarios/',include('apps.usuarios.urls')),
    path('objetivos/p<int:numObjetivo>.html', views.pagObjetivo, name='pagObjetivo'),
    path('noticias/',include('apps.noticias.urls')),
    
    path('emailContacto/', views.emailContacto, name = 'emailContacto'),

    path('permisoDenegado/', views.permisoDenegado, name = 'permisoDenegado'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

repositorio/raiz/apps/usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class Usuario(AbstractUser):
    pass

    def es_colaborador(self):
        return self.groups.filter(name='colaborador').exists()

repositorio/raiz/apps/usuarios/forms.py
from turtle import color
from django import forms 
from django.contrib.auth.forms import UserCreationForm
#La función gettext_lazy se utiliza para traducir cadenas de texto en aplicaciones de Django. Permite marcar las cadenas de texto para su traducción, de modo que puedan ser adaptadas a diferentes idiomas en el futuro.
from django.utils.translation import gettext_lazy as _
from .models import Usuario

#formato usual de registro de usuarios
class RegistroForm(UserCreationForm):
    email = forms.EmailField(label='Email',required=True, 
                    widget=forms.TextInput(attrs={'placeholder': 'Email'}))
    
    first_name = forms.CharField(label='Nombre',required=True, 
                    widget=forms.TextInput(attrs={'placeholder': 'Nombre'}))
    
    last_name = forms.CharField(label='Apellido', required=True, 
                    widget=forms.TextInput(attrs={'placeholder': 'Apellido'}))
    password1 = forms.CharField(
        label='Contraseña', widget=forms.PasswordInput, required=True)
    password2 = forms.CharField(
        label='Confirmar Contraseña', widget=forms.PasswordInput, required=True)

    class Meta:
        model = Usuario
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2',
        ]

repositorio/raiz/apps/usuarios/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.forms import SetPasswordForm
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages
from django.views.generic import CreateView,FormView
from django.urls import reverse_lazy
from django.contrib.auth import views as auth
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from apps.usuarios.models import Usuario
from django.contrib.auth.models import Group
from .forms import RegistroForm
from django.db import IntegrityError
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from blog.decorators import *



class registrarse(CreateView):
    form_class = RegistroForm #toma el modelo definido en forms.
    
    success_url = reverse_lazy('usuarios:loguearse') #redirige al login luego del registro exitoso.
	
    template_name = 'usuarios/registrarse.html'

def loguearse(request):
    return render(request,'usuarios/loguearse.html')


class CustomPasswordResetCompleteView(auth.PasswordResetCompleteView):

    def get(self, request, *args, **kwargs):
        return redirect('usuarios:password_success')  # Redirige a la vista 'usuarios:loguearse' luego del mensaje
    

class password_change(LoginRequiredMixin, FormView):
    template_name = 'usuarios/cambiarPassword/password_change.html'
    form_class = SetPasswordForm
    success_url = reverse_lazy('home')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.save()
        update_session_auth_hash(self.request, form.user)
        return super().form_valid(form)
    
def password_success(request):
    return render(request,'usuarios/cambiarPassword/password_success.html') 
    
@staff 
def listarUsuarios(request):
    usuarios_list = Usuario.objects.all()   # Muestra todas las noticias

    # Configurar la paginación: 10 usuarios por página
    paginator = Paginator(usuarios_list, 10)
    page = request.GET.get('pagina')

    try:
        usuarios = paginator.page(page)
    except PageNotAnInteger:
        # Si el parámetro 'page' no es un número, mostrar la primera página
        usuarios = paginator.page(1)
    except EmptyPage:
        # Si el número de página está fuera de rango, mostrar la última página
        usuarios = paginator.page(paginator.num_pages)

    context = {'usuarios': usuarios}
    return render(request, 'usuarios/listar.html', context)


@staff  
def eliminarUsuario(request, pk):
    usuario = get_object_or_404(Usuario, pk=pk) #la funcion guarda en su variable pk el id de la noticia para luego borrarla
    usuario.delete()
    messages.success(request, 'El usuario ha sido eliminado')
    return redirect('usuarios:listarUsuarios')

@login_required
def modificarUsuario(request, pk):
    usuario = get_object_or_404(Usuario, pk=pk)

    if request.method == 'POST':
        # Obtener los datos enviados por el formulario
        username = request.POST['username']
        email = request.POST['email']
        es_colaborador = 'es_colaborador' in request.POST

        try:
        # Actualizar el usuario con los datos modificados
            usuario.username = username
            usuario.email = email
            
            colaborador_group = Group.objects.get(name='colaborador')
            if es_colaborador:
                colaborador_group.user_set.add(usuario)
            else:
                colaborador_group.user_set.remove(usuario)
            
            usuario.save()

            # Redireccionar a la lista de usuarios o a otra página de tu elección
            return redirect('usuarios:listarUsuarios')
        except IntegrityError:
            # Si se produce una excepción de integridad debido a que el nombre de usuario ya existe, mostrar un mensaje de error.
            mensajeError = "El nombre de usuario ya está en uso. Por favor, elige otro nombre."
            context = {'usuario': usuario, 'es_colaborador': usuario.groups.filter(name='colaborador').exists(), 'mensajeError': mensajeError}
            return render(request, 'usuarios/modificar.html', context)

    # Si la petición es GET, mostrar el formulario con los datos actuales del usuario
    context = {'usuario': usuario, 'es_colaborador': usuario.groups.filter(name='colaborador').exists()}
    return render(request, 'usuarios/modificar.html', context)

repositorio/raiz/templates/usuarios/listar.html
{%extends 'baseLogin.html' %}
{% load static %}

{% block contenido %}


<head>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
  
</head>

<div style="margin-top: 60px;">
  <div class="container mt-4">
    <div class="d-flex justify-content-between mb-3">
      <a href="{% url 'home' %}" class="btn btn-dark">Volver</a>
      <div class="col-md-4">
        <div class="input-group">
          <input class="form-control" type="text" id="searchInput" placeholder="Buscar usuario" aria-label="Search for..." aria-describedby="btnNavbarSearch" />
          <button class="btn btn-dark" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
        </div>
      </div>
    </div>
    
    <table class="table table-striped mt-2">
      <thead>
        <tr>
          <th>Nombre de Usuario</th>
          <th>Email</th>
          <th class="text-center">¿Es Colaborador?</th>
          <th style="width: 100px;">Acciones</th>
        </tr>
      </thead>
      <tbody>
        {% for usuario in usuarios %}
          {% if not user.username == usuario.username %}
            <tr>
              <td>{{ usuario.username }}</td>
              <td>{{ usuario.email }}</td>
              <td class="text-center">{% if usuario.es_colaborador %}Sí{% else %}No{% endif %}</td>
              <td>
                <!-- Iconos para editar y eliminar -->
                <a href="{% url 'usuarios:modificarUsuario' usuario.pk %}" class="btn btn-primary btn-sm mx-1">
                  <i class="fas fa-edit"></i>
                </a>
                <a href="{% url 'usuarios:eliminarUsuario' usuario.pk %}" class="btn btn-danger btn-sm mx-1">
                  <i class="fas fa-trash"></i>
                </a>
              </td>
            </tr>
          {%endif%}
        {% endfor %}
      </tbody>
    </table>
    <!-- Paginación -->
    <nav aria-label="Paginación" class="mt-4">
      <ul class="pagination justify-content-center">
        {% if usuarios.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?pagina=1" aria-label="Primera">
              <span aria-hidden="true">&laquo;&laquo;</span>
            </a>
          </li>
          <li class="page-item">
            <a class="page-link" href="?pagina={{ usuarios.previous_page_number }}" aria-label="Anterior">
              <span aria-hidden="true">&laquo;</span>
            </a>
          </li>
        {% endif %}
        {% for num in usuarios.paginator.page_range %}
          {% if usuarios.number == num %}
            <li class="page-item active"><span class="page-link">{{ num }}</span></li>
          {% else %}
            <li class="page-item"><a class="page-link" href="?pagina={{ num }}">{{ num }}</a></li>
          {% endif %}
        {% endfor %}
        {% if usuarios.has_next %}
          <li class="page-item">
            <a class="page-link" href="?pagina={{ usuarios.next_page_number }}" aria-label="Siguiente">
              <span aria-hidden="true">&raquo;</span>
            </a>
          </li>
          <li class="page-item">
            <a class="page-link" href="?pagina={{ usuarios.paginator.num_pages }}" aria-label="Última">
              <span aria-hidden="true">&raquo;&raquo;</span>
            </a>
          </li>
        {% endif %}
      </ul>
    </nav>
  </div>
</div>

  <!-- Agregar los enlaces a los archivos de Bootstrap JS al final del cuerpo del documento -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <script>
    
   // Función para filtrar los usuarios
  function filterUsers() {
    var input, filter, table, tr, td, i, txtValue;
    input = document.getElementById('searchInput');
    filter = input.value.toLowerCase();
    table = document.querySelector('table');
    tr = table.getElementsByTagName('tr');

    for (i = 0; i < tr.length; i++) {
      td = tr[i].getElementsByTagName('td')[0]; 
      if (td) {
        txtValue = td.textContent || td.innerText;
        if (txtValue.toLowerCase().indexOf(filter) > -1) {
          tr[i].style.display = '';
        } else {
          tr[i].style.display = 'none';
        }
      }
    }
  }

  document.getElementById('btnNavbarSearch').addEventListener('click', filterUsers);

  document.getElementById('searchInput').addEventListener('input', filterUsers);

  document.getElementById('searchInput').addEventListener('keyup', function(event) {
    // Detectar si se presionó la tecla "Enter" (código 13)
    if (event.keyCode === 13) {
      filterUsers();
    }
  });

  document.getElementById('searchInput').addEventListener('blur', function() {
    // Si el campo de búsqueda está vacío, mostrar todos los usuarios originales
    if (this.value.trim() === '') {
      var table = document.querySelector('table');
      var tr = table.getElementsByTagName('tr');

      for (var i = 0; i < tr.length; i++) {
        tr[i].style.display = '';
      }
    }
  });

  // Restaurar el filtro de búsqueda después de cambiar de página
  window.addEventListener('popstate', function(event) {
    var input = document.getElementById('searchInput');
    var filter = input.value.toLowerCase();
    var table = document.querySelector('table');
    var tr = table.getElementsByTagName('tr');

    for (var i = 0; i < tr.length; i++) {
      var td = tr[i].getElementsByTagName('td')[0];
      if (td) {
        var txtValue = td.textContent || td.innerText;
        if (txtValue.toLowerCase().indexOf(filter) > -1) {
          tr[i].style.display = '';
        } else {
          tr[i].style.display = 'none';
        }
      }
    }
  });
  </script>


{% endblock contenido %}

repositorio/raiz/templates/usuarios/loguearse.html
{%extends 'baseLogin.html' %}
{% block contenido %}

{% load static %}

<head>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" >
    <link rel="stylesheet" href="{% static 'css/loguearse.css' %}">
</head>  
<body>
    <form method="POST" class="formulario">{%csrf_token%}
        {{form.errors}}
        
        <h1>Login</h1>
        <div class="contenedor">
     
            <div class="input-contenedor">
                <i class="fas fa-envelope icon"></i>
                <input type="text" name="username" placeholder="Usuario">
            </div>
            
            <div class="input-contenedor">
                <i class="fas fa-key icon"></i>
                <input type="password" name="password" placeholder="Contraseña">
            </div>

            <input type="submit" name="" value="Ingresar" class="button">
            <p>¿Olvidaste tu contraseña? <a class="link" href="{%url 'usuarios:password_reset'%}">Recuperar Contraseña</a></p>
            <p>¿No tienes una cuenta? <a class="link" href="{%url 'usuarios:registrarse'%}">Registrate </a></p>

        </div>

    </form>
</body>
</html>



{%endblock contenido%}

repositorio/raiz/templates/usuarios/modificar.html
{%extends 'baseLogin.html' %}
{% load static %}
{% block contenido %}

<head>
  <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <script src="{% static 'js/scriptsBlog.js' %}"></script>
</head>

<div class="margen" style="margin-top: 60px;">
  <div class="container"> <!-- Agrega un contenedor para centrar el formulario -->
    <div class="text-center">
      <h2><b>EDICIÓN DE USUARIO</b></h2>
    </div>
    <form method="post" id="formulario">

      {% csrf_token %}

      {% if mensajeError %}
      <div class="alert alert-danger">
        <strong>Error:</strong> {{ mensajeError }}
      </div>
      {% endif %}
      <!-- Nombre de Usuario -->
      <div class="mb-3">
        <label for="username" class="form-label">Nombre de Usuario</label>
        <input type="text" class="form-control" id="username" name="username" value="{{ usuario.username }}" required>
      </div>

      <!-- Email -->
      <div class="mb-3">
        <label for="email" class="form-label">Email</label>
        <input type="email" class="form-control" id="email" name="email" value="{{ usuario.email }}" required>
      </div>

      {%if user.is_staff%}
      <!-- ¿Es Colaborador? -->
          <div class="mb-3">
          <label class="form-check-label">¿Es Colaborador?</label>
          <div class="form-check">
              <input type="checkbox" class="form-check-input" id="es_colaborador" name="es_colaborador" {% if usuario.es_colaborador %}checked{% endif %}>
          </div>
          </div>
      {%else%}
          <div class="mb-3">
              <a href="{% url 'usuarios:password_change' %}" class="btn btn-dark submit-btn">Cambiar contraseña</a>
          </div>             
      {% endif %}

      <div class="mb-3">
        {%if user.is_staff%}
          <a href="{% url 'usuarios:listarUsuarios' %}" class="btn btn-outline-primary">Volver</a>
        {%else%}
          <a href="{% url 'home' %}" class="btn btn-outline-primary">Volver</a>
        {%endif%}
        <button type="button" class="btn btn-secondary" onclick="cancelarEdicion()" formnovalidate>Cancelar</button>
        <input type="button" value="Guardar cambios" class="btn btn-primary" onclick="confirmarGuardarCambios()">
      </div>
    </form>
  </div>
</div>
{% endblock contenido%}

repositorio/raiz/templates/usuarios/registrarse.html
{%extends 'baseLogin.html' %}
{% block contenido %}

{% load static %}

<head>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" >
	<link rel="stylesheet" href="{% static 'css/loguearse.css' %}">

	
</head>  
<body>

 <form method="post" class="formulario">{%csrf_token%}
    {{form.errors}}

    <h1>Registrate</h1>

    <div class="contenedor">

        <div class="input-contenedor">

            <i class="fas fa-user icon"></i>
            <input type="text" name="first_name" placeholder="Nombre/s">
            
        </div>
        <div class="input-contenedor">

            <i class="fas fa-user icon"></i>
            <input type="text" name="last_name" placeholder="Apellido/s">
            
        </div>
     
        <div class="input-contenedor">

            <i class="fas fa-user icon"></i>
            <input type="text" name="username" placeholder="Nombre de Usuario">
         
        </div>
         
        <div class="input-contenedor">

            <i class="fas fa-envelope icon"></i>
            <input type="text" name="email" placeholder="Correo Electronico">
         
        </div>
         
        <div class="input-contenedor">

            <i class="fas fa-key icon"></i>
            <input type="password" name="password1" placeholder="Contraseña" class="password-input">

        </div>
        
        <div class="input-contenedor">

            <i class="fas fa-key icon"></i>
            <input type="password" name="password2" placeholder="Reingrese su contraseña" class="password-input">

        </div>
         
        </div>

        <input method="get" type="submit" value="Registrarme" class="button">
        <p>Al registrarte, aceptas nuestras <a class="link" href="#">Condiciones de uso y Política de privacidad. </a></p>
        <p>¿Ya tienes una cuenta?<a class="link" href="{%url 'usuarios:loguearse'%}"> Iniciar Sesion</a></p>

    </div>

</form>

</body>
</html>
{% endblock contenido %}