repositorio/raiz/apps/noticias/urls.py
from django.urls import path
from . import views

app_name='noticias'

urlpatterns = [
    # #URL CRUD'S

    #create
    path('agregarNoticia/', views.agregarNoticia, name='agregarNoticia'),
    path('agregarComentario/<int:pk>/', views.agregarComentario, name='agregarComentario'),

    #read
    path('listarNoticias/', views.listarNoticias, name='listarNoticias'),
    path('buscarNoticias/', views.buscarNoticias, name='buscarNoticias'),
    path('mostrarNoticia/<int:pk>/', views.mostrarNoticia, name='mostrarNoticia'),

    # #update
    path('modificarNoticia/<int:pk>/', views.modificarNoticia.as_view(), name='modificarNoticia'),

    #delete
    path('eliminarNoticia/<int:pk>/', views.eliminarNoticia, name='eliminarNoticia'),
    path('eliminarComentario/<int:pk>', views.eliminarComentario, name='eliminarComentario'),

]

repositorio/raiz/apps/usuarios/urls.py
from django.urls import path, reverse_lazy
from . import views

from django.contrib.auth import views as auth

app_name= 'usuarios'


urlpatterns = [
    
    path('registrarse/',views.registrarse.as_view(), name='registrarse'),
    path('login/',auth.LoginView.as_view(template_name='usuarios/loguearse.html'),name='loguearse'), #en vez de pasarle una vista mia paso una de django
    path('logout/',auth.LogoutView.as_view(),name="logout"),
    path('listar/',views.listarUsuarios,name="listarUsuarios"),
    path('eliminar/<int:pk>',views.eliminarUsuario,name="eliminarUsuario"),    
    path('modificar/<int:pk>',views.modificarUsuario,name="modificarUsuario"),   
    
    #modificar Password
    path('password_change/', views.password_change.as_view(), name='password_change'),
    path('password_success/', views.password_success, name='password_success'),
    #recuperacion de Password
    path(
        'password_reset/',
        auth.PasswordResetView.as_view(
        template_name='usuarios/reestablecerPassword/password_reset_form.html',
        email_template_name='usuarios/reestablecerPassword/password_reset_email.html',
        success_url=reverse_lazy('usuarios:password_reset_done')),
        name='password_reset'),
    path(
        'password_reset_done/',
        auth.PasswordResetDoneView.as_view(
        template_name='usuarios/reestablecerPassword/password_reset_done.html'),
        name='password_reset_done'),

    path(
        'password_reset/<uidb64>/<token>',
        auth.PasswordResetConfirmView.as_view(
        template_name='usuarios/reestablecerPassword/password_reset_confirm.html',
        success_url=reverse_lazy('usuarios:password_reset_complete')),
        name='password_reset_confirm'),

    path('password_reset_complete/',
        views.CustomPasswordResetCompleteView.as_view(
        template_name='usuarios/reestablecerPassword/password_reset_complete.html'),
        name='password_reset_complete'),                                
]

repositorio/raiz/blog/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings


from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', views.Home, name = 'home'),
    path('contacto/', views.Contacto, name = 'contacto'),
    path('usuarios/',include('apps.usuarios.urls')),
    path('objetivos/p<int:numObjetivo>.html', views.pagObjetivo, name='pagObjetivo'),
    path('noticias/',include('apps.noticias.urls')),
    
    path('emailContacto/', views.emailContacto, name = 'emailContacto'),

    path('permisoDenegado/', views.permisoDenegado, name = 'permisoDenegado'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

repositorio/raiz/apps/noticias/models.py
from django.db import models
from apps.usuarios.models import Usuario

# Create your models here.
class Objetivo(models.Model):
    nombre = models.CharField(max_length=60)
    descripcion= models.CharField(max_length=250,null=True,blank=True)
    imagen= models.ImageField(upload_to='noticias',null=True)
    estado = models.CharField(max_length=20,  default='habilitado', blank=True, null=True, db_comment='habilitado, deshabilitado')

    
    def __str__(self):
        return self.nombre
    
class Noticia(models.Model):
    titulo = models.CharField(max_length=120)
    creado = models.DateField(auto_now_add=True)
    cuerpo = models.TextField()
    autor = models.ForeignKey(Usuario, on_delete=models.CASCADE, null=True, blank=True)
    imagen = models.ImageField(upload_to='noticias', null=True)
    objetivo=models.ForeignKey(Objetivo,on_delete=models.CASCADE,null=True)
    estado = models.CharField(max_length=20,  default='habilitado', blank=True, null=True, db_comment='habilitado, deshabilitado')

    
    def __str__(self):
        return self.titulo
    
    def textCorto(self):
        return self.cuerpo[:180]+"..."
    
    def delete(self, *args, **kwargs):
        # Antes de eliminar la noticia, también eliminamos la imagen asociada (si existe)
        if self.imagen:
            self.imagen.delete()
        super().delete(*args, **kwargs)
       

class Comentario(models.Model):
	noticia = models.ForeignKey(Noticia, related_name = 'mis_comentarios', on_delete = models.CASCADE)
	texto = models.TextField()
	creado = models.DateTimeField(auto_now_add = True)
	usuario = models.ForeignKey(Usuario, related_name = 'usuario_comentario' , on_delete = models.CASCADE)

	def __str__(self):
		return self.texto
    

repositorio/raiz/apps/noticias/forms.py
from django import forms
from .models import Noticia



class NoticiaAgregarForm(forms.ModelForm):
    class Meta:
        model = Noticia
        fields = ['titulo', 'cuerpo', 'autor', 'imagen', 'objetivo', 'estado']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['objetivo'].empty_label = 'Seleccione'
        # No mostraremos el campo 'estado' en el formulario
        self.fields['estado'].widget = forms.HiddenInput()
        self.fields['estado'].initial = 'habilitado'  # O el valor que desees
        self.fields['autor'].widget = forms.HiddenInput()
        

    def clean_titulo(self):
        titulo = self.cleaned_data.get('titulo')
        if len(titulo) < 3:
            raise forms.ValidationError("El título debe tener al menos 3 caracteres.")
        return titulo

    def clean_cuerpo(self):
        cuerpo = self.cleaned_data.get('cuerpo')
        if len(cuerpo) < 20:
            raise forms.ValidationError("El cuerpo debe tener al menos 20 caracteres.")
        return cuerpo
    

class NoticiaForm(forms.ModelForm):
    class Meta:
        model = Noticia
        fields = ['titulo', 'cuerpo', 'autor', 'imagen', 'objetivo', 'estado']


    def __init__(self, *args, **kwargs): #Al modificar el campo en el método __init__, aseguramos que se apliquen los cambios al formulario antes de que se renderice en la vista
        super().__init__(*args, **kwargs)
        self.fields['objetivo'].empty_label = 'Seleccione'
        self.fields['estado'].empty_label = 'Seleccione el estado'
        self.fields['estado'].choices = [('habilitado', 'Habilitado'), ('deshabilitado', 'Deshabilitado')]

repositorio/raiz/apps/noticias/views.py
#VER QUE NO SIRVE
from django import forms
from django.shortcuts import render,get_object_or_404,redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import UpdateView
from django.core.paginator import Paginator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .forms import NoticiaAgregarForm
from django.urls import reverse_lazy
from django.contrib import messages
from django.db.models import Q
from django.utils.decorators import method_decorator
from django.urls import reverse
from .models import Noticia,Comentario
from blog.decorators import *


@login_required
def agregarNoticia(request):
    if request.method == 'POST':
        form = NoticiaAgregarForm(request.POST, request.FILES)
        if form.is_valid():

            noticia = form.save(commit=False)
            noticia.autor = request.user  # Asignar el usuario actual como autor de la noticia
            noticia.save()
            #messages.success(request, 'Noticia modificada exitosamente.')
            return redirect('noticias:listarNoticias')
    else:
        form = NoticiaAgregarForm()
    return render(request, 'noticias/agregarNoticia.html', {'form': form})

@login_required
def agregarComentario(request,pk):
	texto = request.POST.get('comentario')
	noticia = Noticia.objects.get(pk = pk)
	c = Comentario.objects.create(noticia = noticia, texto = texto, usuario = request.user)
	return redirect('noticias:mostrarNoticia' , pk=pk)



#read

def buscarNoticias(request):
    query = request.POST.get('buscar')
    noticias = None

    if query:
        noticias = Noticia.objects.filter(
            Q(titulo__icontains=query) |
            Q(cuerpo__icontains=query) |
            Q(objetivo__nombre__icontains=query) |
            Q(autor__username__icontains=query)
        )

    context = {
        'noticias': noticias
    }
    return render(request, 'noticias/listarNoticias.html', context)


def listarNoticias(request):
    noticias_list = Noticia.objects.all().order_by('-creado')

    # Configurar la paginación: 9 noticias por página
    paginator = Paginator(noticias_list, 6)
    page = request.GET.get('page')

    try:
        noticias = paginator.page(page)
    except PageNotAnInteger:
        # Si el parámetro 'page' no es un número, mostrar la primera página
        noticias = paginator.page(1)
    except EmptyPage:
        # Si el número de página está fuera de rango, mostrar la última página
        noticias = paginator.page(paginator.num_pages)

    context = {'noticias': noticias}
    return render(request, 'noticias/listarNoticias.html', context)

def mostrarNoticia(request, pk): #Viene como parametro el pk que ingreso en la url
    noticia = get_object_or_404(Noticia, pk=pk)   # Muestra solo una noticia por su pk
    comentarios = noticia.mis_comentarios.all()  # Obtiene todos los comentarios asociados a esta noticia
    context = {'noticia': noticia, 'comentarios': comentarios}
    return render(request, 'noticias/mostrarNoticia.html', context)

#update

@method_decorator(login_required, name='dispatch')
@method_decorator(staff_colaborador_autor, name='dispatch')
class modificarNoticia(UpdateView):
    model= Noticia
    template_name= 'noticias/modificarNoticia.html'
    fields = ['titulo', 'cuerpo', 'imagen', 'objetivo', 'estado']
    success_url= reverse_lazy('noticias:listarNoticias')
    
    def form_valid(self, form):
        titulo = form.cleaned_data['titulo']
        cuerpo = form.cleaned_data['cuerpo']
        estado = form.cleaned_data['estado']

        if len(titulo) < 3:
            form.add_error ('titulo', "El titulo debe tener al menos 3 caracteres.")
            return self.form_invalid(form)
        
        if len(cuerpo) < 20:
            form.add_error ('cuerpo', "El cuerpo debe tener al menos 20 caracteres.")
            return self.form_invalid(form)
        
        if estado not in ['habilitado', 'deshabilitado']:  #controla que el estado sea solo 'habilitado', 'deshabilitado' 
            form.add_error('estado', "El estado debe ser 'habilitado' , 'deshabilitado'.")
            return self.form_invalid(form)
        
        #messages.success(self.request, 'Noticia modificada exitosamente.')

        return super().form_valid(form) #Si el 'nombre' es válido, llamamos a super().form_valid(form) para guardar los cambios y redireccionar a la página de mostrar todas

    def get_form(self, form_class=None): #metodo que nos da un select para seleccionar habilitado o deshabilitado
        form = super().get_form(form_class) #metodo para obtener el formulario original generado por Django.
        form.fields['estado'].widget = forms.Select(choices=[('habilitado', 'Habilitado'), ('deshabilitado', 'Deshabilitado')]) # Asignamos el widget forms.Select al campo 'estado'
        return form
    

#delete
@staff_colaborador_autor
def eliminarNoticia(request, pk):
    noticia = get_object_or_404(Noticia, pk=pk) #la funcion guarda en su variable pk el id de la noticia para luego borrarla
    noticia.delete()
    messages.success(request, 'Noticia eliminada exitosamente.')
    return redirect('noticias:listarNoticias')

@staff_colaborador_autor_comentario
def eliminarComentario(request, pk):
    comentario = get_object_or_404(Comentario, pk=pk) #la funcion guarda en su variable pk el id de la noticia para luego borrarla
    noticia_pk = comentario.noticia.pk  # Obtenemos el pk de la noticia asociada al comentario
    comentario.delete()
    messages.success(request, 'comentario eliminado exitosamente.')
    return redirect(reverse('noticias:mostrarNoticia', kwargs={'pk': noticia_pk}))

repositorio/raiz/templates/noticias/agregarNoticia.html
{%extends 'baseLogin.html' %}
{% load static %}
{% block contenido %}



<div class="container" style="margin-top: 60px; margin-: 20px;"> 
    <div class="text-center">
        <h2><b>NUEVA NOTICIA</b></h2>
    </div>
    <form method="post" enctype="multipart/form-data" id="formulario" onsubmit="return validarFormulario();">

        {% csrf_token %}

        <!-- Título -->
        <div class="mb-3">
            <label for="{{ form.titulo.id_for_label }}" class="form-label">Título</label>
            <input type="text" class="form-control" id="{{ form.titulo.auto_id }}" name="{{ form.titulo.name }}" minlength="3" required>

        </div>

        <!-- Cuerpo -->
        <div class="mb-3">
            <label for="{{ form.cuerpo.id_for_label }}" class="form-label">Cuerpo</label>
            <textarea class="form-control" id="{{ form.cuerpo.auto_id }}" name="{{ form.cuerpo.name }}"rows="10" minlength="20" required></textarea>
            
      
        </div>
        <!-- Imagen -->
        <div class="mb-3">
            <label for="{{ form.imagen.id_for_label }}" class="form-label">Imagen</label>
            <input type="file" class="form-control" id="{{ form.imagen.auto_id }}" name="{{ form.imagen.name }}" required>
        </div>

        <!-- Objetivo -->
        <div class="mb-3">
            <label for="{{ form.objetivo.id_for_label }}" class="form-label">Objetivo</label>
            {{ form.objetivo }}
        </div>
      

        <div class="mb-3">
            <a href="{% url 'noticias:listarNoticias' %}" class="btn btn-outline-primary">Volver</a>
            <button type="button" class="btn btn-secondary" onclick="cancelarEdicion()" formnovalidate>Cancelar</button>
            <input type="submit" value="Guardar cambios" class="btn btn-primary" onclick="validarFormulario()">

        </div>
    </form>
</div>

{% endblock %}

repositorio/raiz/templates/noticias/listarNoticias.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}

<head>
    <link rel="stylesheet" href="{% static 'css/noticias/noticias.css' %}">
</head>

<section id="noticias">
    <div class="container noticias-container">
        {% for noticia in noticias %}
            <div class="noticia">
                {% if user.is_authenticated %}
                    {% if user.is_staff or user == noticia.autor or user.es_colaborador %}
                        <div class="containerOpcNoticia" data-dropdown data-dropdown-button>
                            <a class="opcNoticia" data-dropdown-button></a>
                            <div class="menuOpciones opcionesN">
                                <div class="">
                                    <form action="{% url 'noticias:modificarNoticia' noticia.pk %}" method="get">
                                        {% csrf_token %}
                                        <button type="submit" class="botonEditar">Editar</button>
                                    </form>
                                    <form action="{% url 'noticias:eliminarNoticia' noticia.pk %}" method="post">
                                        {% csrf_token %}
                                        <button type="submit" class="botonEliminar">Eliminar</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% endif %}
                <h2>{{noticia.titulo}}</h2>

                <div class="imagen">
                    <img class="image" src="{{noticia.imagen.url}}">
                    <div class="fecha">{{noticia.autor}} | {{noticia.creado}}</div>
                    <div style="text-transform:initial; font-size: 12px;"><strong><b>OBJETIVO: {{noticia.objetivo}}</b> </strong></div>
                </div>
                <div class="contenido">
                    <p>{{noticia.textCorto}}</p>
                </div>
                <div class="acciones">
                    <form action="{% url 'noticias:mostrarNoticia' noticia.pk %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary">Ver más...</button>
                    </form>
                </div>
            </div>
        {% endfor %}

        
    </div>
    <!-- Paginación -->
    <nav aria-label="Paginación" class="mt-4">
        <ul class="pagination justify-content-center">
            {% if noticias.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1" aria-label="Primera">
                        <span aria-hidden="true">&laquo;&laquo;</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ noticias.previous_page_number }}" aria-label="Anterior">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            {% endif %}
            {% for num in noticias.paginator.page_range %}
                {% if noticias.number == num %}
                    <li class="page-item active"><span class="page-link">{{ num }}</span></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                {% endif %}
            {% endfor %}
            {% if noticias.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ noticias.next_page_number }}" aria-label="Siguiente">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ noticias.paginator.num_pages }}" aria-label="Última">
                        <span aria-hidden="true">&raquo;&raquo;</span>
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
</section>

{% endblock contenido %}

repositorio/raiz/templates/noticias/modificarNoticia.html
{% extends 'baseLogin.html' %}
{%load static %}
{%block contenido%}


<div class="container" style="margin-top: 60px;"> <!-- Agrega un contenedor para centrar el formulario -->
  <div class="text-center">
    <h2><b>EDICIÓN</b></h2>
  </div>
  <form method="post" enctype="multipart/form-data" id="formulario">

    {% csrf_token %}

    <!-- Título -->
    <div class="mb-3">
      <label for="{{ form.titulo.id_for_label }}" class="form-label">Título</label>
      <input type="text" class="form-control" id="{{ form.titulo.auto_id }}" name="{{ form.titulo.name }}" value="{{ object.titulo }}">
    </div>

    <!-- Cuerpo -->
    <div class="mb-3">
      <label for="{{ form.cuerpo.id_for_label }}" class="form-label">Cuerpo</label>
      <textarea class="form-control" id="{{ form.cuerpo.auto_id }}" name="{{ form.cuerpo.name }}" rows="10">{{ object.cuerpo }}</textarea>
    </div>

    <!-- Imagen -->
    <div class="mb-3">
      <div class="mb-3">
        <label class="form-label">Imagen Actual: </label>
        <img src="{{ object.imagen.url }}" alt="Imagen Actual" class="img-thumbnail">
      </div>
      <label for="{{ form.imagen.id_for_label }}" class="form-label">Modificar imagen: </label>
      <input type="file" class="form-control" id="{{ form.imagen.auto_id }}" name="{{ form.imagen.name }}">
    </div>

    <!-- Objetivo -->
    <div class="mb-3">

      <label for="{{ form.objetivo.id_for_label }}" class="form-label">Objetivo</label>
      {{ form.objetivo }}
    </div>

    <!-- Estado -->
    <div class="mb-3">
      <label for="{{ form.estado.id_for_label }}" class="form-label">Estado</label>
      {{ form.estado }}
    </div>

    <div class="mb-3">
      <a href="{% url 'noticias:mostrarNoticia' object.pk %}" class="btn btn-outline-primary">Volver</a>
      <button type="button" class="btn btn-secondary" onclick="cancelarEdicion()" formnovalidate>Cancelar</button>
      <input type="button" value="Guardar cambios" class="btn btn-primary" onclick="confirmarGuardarCambios()">
      
    </div>
  </form>
</div>


{% endblock %}

repositorio/raiz/templates/noticias/mostrarNoticia.html
{%extends 'base.html'%}
{%load static %}
{%block contenido%}


<head>
    <link rel="stylesheet" href="{% static 'css/noticias/detalle.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
</head>

<section id="destacado">
    <div class="container2">
        <div class="noticia noticia-destacada">
            <!-- Para la edición y eliminación -->
            {% if user.is_authenticated %}
                {% if user.is_staff or user == noticia.autor or user.es_colaborador %}
                    <div class="containerOpcNoticia" data-dropdown data-dropdown-button>
                        <a class="opcNoticia" data-dropdown-button></a>
                        <div class="menuOpciones opcionesN">
                            <div class="">
                                <form action="{% url 'noticias:modificarNoticia' noticia.pk %}" method="get">
                                    {% csrf_token %}
                                    <button type="submit" class="botonEditar">Editar</button>
                                </form>
                                <form action="{% url 'noticias:eliminarNoticia' noticia.pk %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="botonEliminar">Eliminar</button>
                                </form>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endif %}
            <h2>{{noticia.titulo}}</h2>
            
            <div class="fecha"> 
                {{noticia.autor}} | {{noticia.creado}}
            </div>
            <div class="contenido">
                <div class="imagen-macro">
                    <img src="{{noticia.imagen.url}}" alt="Imagen Macro">
                    <div class="datos-autor">
                        <p>Objetivo relacionado: {{noticia.objetivo}} </p>
                        
                    </div>
                </div>
                <div class="columna-texto">
                    <div class="columna-izquierda">
                        <h4>---</h4>
                        <p>{{noticia.cuerpo}}</p>
                    </div>
                </div>
            </div>
            <div class="acciones">
                <form action="{% url 'noticias:listarNoticias'%}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary">Volver</button>

                </form>

                <form action="#" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary">Compartir</button>

                </form>
            </div>
        </div>

        <div class="my-3 p-3 bg-body rounded shadow-sm">
            <h6 class="border-bottom pb-2 mb-0">Comentarios</h6>
            
            {% for comentario in comentarios %}
            <div class="d-flex text-body-secondary pt-3">
                <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false">
                    <title>Placeholder</title>
                    <rect width="100%" height="100%" fill="#007bff" />
                    <text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text>
                </svg>
                <div class="flex-grow-1"> <!-- Para que el contenido ocupe todo el espacio disponible -->
                    <p class="pb-3 mb-0 small lh-sm border-bottom">
                        <strong class="d-block text-gray-dark">@{{ comentario.usuario }}</strong>
                        {{ comentario.texto }}
                    </p>
                </div>
                {% if user.is_staff or user == comentario.usuario or user.es_colaborador %}
                    <form action="{% url 'noticias:eliminarComentario' comentario.pk %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-link text-danger">
                            <i class="fas fa-trash-alt"></i>
                        </button>
                    </form>
                {% endif %}
            </div>
            {% endfor %}
    
            {% if user.is_authenticated %}
                
                <small class="d-block text-end mt-3">
                    <form method="POST" action="{% url 'noticias:agregarComentario' noticia.pk %}" >{% csrf_token %}
                        <!-- Campo oculto para el identificador de la noticia -->
                        <input type="hidden" name="pk" value="{{ noticia.pk }}">
                        <div class="mb-1">
                            <label for="exampleFormControlInput1" class="form-label" style="font-size: 18px;">Usuario: {{user.username}}</label>
                        </div>
                        <div class="mb-3">
                            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="comentario"></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">Comentar</button>
                    </form>           
                </small>
            {% elif not user.is_authenticated %}
                <small class="d-block text-end mt-3">
                    <p>*Para comentar debes <a type="submit" href="{% url 'usuarios:loguearse' %}"><u><b> ingresar </b></a></u></p>
                </small>
            {% endif %}
        </div>
    </div>

</section>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js"></script>

{%endblock contenido%}