repositorio/raiz/apps/usuarios/urls.py
from django.urls import path, reverse_lazy
from . import views

from django.contrib.auth import views as auth

app_name= 'usuarios'


urlpatterns = [
    
    path('registrarse/',views.registrarse.as_view(), name='registrarse'),
    path('login/',auth.LoginView.as_view(template_name='usuarios/loguearse.html'),name='loguearse'), #en vez de pasarle una vista mia paso una de django
    path('logout/',auth.LogoutView.as_view(),name="logout"),
    path('listar/',views.listarUsuarios,name="listarUsuarios"),
    path('eliminar/<int:pk>',views.eliminarUsuario,name="eliminarUsuario"),    
    path('modificar/<int:pk>',views.modificarUsuario,name="modificarUsuario"),   
    
    #modificar Password
    path('password_change/', views.password_change.as_view(), name='password_change'),
    path('password_success/', views.password_success, name='password_success'),
    #recuperacion de Password
    path(
        'password_reset/',
        auth.PasswordResetView.as_view(
        template_name='usuarios/reestablecerPassword/password_reset_form.html',
        email_template_name='usuarios/reestablecerPassword/password_reset_email.html',
        success_url=reverse_lazy('usuarios:password_reset_done')),
        name='password_reset'),
    path(
        'password_reset_done/',
        auth.PasswordResetDoneView.as_view(
        template_name='usuarios/reestablecerPassword/password_reset_done.html'),
        name='password_reset_done'),

    path(
        'password_reset/<uidb64>/<token>',
        auth.PasswordResetConfirmView.as_view(
        template_name='usuarios/reestablecerPassword/password_reset_confirm.html',
        success_url=reverse_lazy('usuarios:password_reset_complete')),
        name='password_reset_confirm'),

    path('password_reset_complete/',
        views.CustomPasswordResetCompleteView.as_view(
        template_name='usuarios/reestablecerPassword/password_reset_complete.html'),
        name='password_reset_complete'),                                
]

repositorio/raiz/blog/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings


from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', views.Home, name = 'home'),
    path('contacto/', views.Contacto, name = 'contacto'),
    path('usuarios/',include('apps.usuarios.urls')),
    path('objetivos/p<int:numObjetivo>.html', views.pagObjetivo, name='pagObjetivo'),
    path('noticias/',include('apps.noticias.urls')),
    
    path('emailContacto/', views.emailContacto, name = 'emailContacto'),

    path('permisoDenegado/', views.permisoDenegado, name = 'permisoDenegado'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

repositorio/raiz/apps/usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class Usuario(AbstractUser):
    pass

    def es_colaborador(self):
        return self.groups.filter(name='colaborador').exists()

repositorio/raiz/apps/usuarios/forms.py
from turtle import color
from django import forms 
from django.contrib.auth.forms import UserCreationForm
#La función gettext_lazy se utiliza para traducir cadenas de texto en aplicaciones de Django. Permite marcar las cadenas de texto para su traducción, de modo que puedan ser adaptadas a diferentes idiomas en el futuro.
from django.utils.translation import gettext_lazy as _
from .models import Usuario

#formato usual de registro de usuarios
class RegistroForm(UserCreationForm):
    email = forms.EmailField(label='Email',required=True, 
                    widget=forms.TextInput(attrs={'placeholder': 'Email'}))
    
    first_name = forms.CharField(label='Nombre',required=True, 
                    widget=forms.TextInput(attrs={'placeholder': 'Nombre'}))
    
    last_name = forms.CharField(label='Apellido', required=True, 
                    widget=forms.TextInput(attrs={'placeholder': 'Apellido'}))
    password1 = forms.CharField(
        label='Contraseña', widget=forms.PasswordInput, required=True)
    password2 = forms.CharField(
        label='Confirmar Contraseña', widget=forms.PasswordInput, required=True)

    class Meta:
        model = Usuario
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2',
        ]

repositorio/raiz/apps/usuarios/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.forms import SetPasswordForm
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages
from django.views.generic import CreateView,FormView
from django.urls import reverse_lazy
from django.contrib.auth import views as auth
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from apps.usuarios.models import Usuario
from django.contrib.auth.models import Group
from .forms import RegistroForm
from django.db import IntegrityError
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from blog.decorators import *



class registrarse(CreateView):
    form_class = RegistroForm #toma el modelo definido en forms.
    
    success_url = reverse_lazy('usuarios:loguearse') #redirige al login luego del registro exitoso.
	
    template_name = 'usuarios/registrarse.html'

def loguearse(request):
    return render(request,'usuarios/loguearse.html')


class CustomPasswordResetCompleteView(auth.PasswordResetCompleteView):

    def get(self, request, *args, **kwargs):
        return redirect('usuarios:password_success')  # Redirige a la vista 'usuarios:loguearse' luego del mensaje
    

class password_change(LoginRequiredMixin, FormView):
    template_name = 'usuarios/cambiarPassword/password_change.html'
    form_class = SetPasswordForm
    success_url = reverse_lazy('home')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.save()
        update_session_auth_hash(self.request, form.user)
        return super().form_valid(form)
    
def password_success(request):
    return render(request,'usuarios/cambiarPassword/password_success.html') 
    
@staff 
def listarUsuarios(request):
    usuarios_list = Usuario.objects.all()   # Muestra todas las noticias

    # Configurar la paginación: 10 usuarios por página
    paginator = Paginator(usuarios_list, 10)
    page = request.GET.get('pagina')

    try:
        usuarios = paginator.page(page)
    except PageNotAnInteger:
        # Si el parámetro 'page' no es un número, mostrar la primera página
        usuarios = paginator.page(1)
    except EmptyPage:
        # Si el número de página está fuera de rango, mostrar la última página
        usuarios = paginator.page(paginator.num_pages)

    context = {'usuarios': usuarios}
    return render(request, 'usuarios/listar.html', context)


@staff  
def eliminarUsuario(request, pk):
    usuario = get_object_or_404(Usuario, pk=pk) #la funcion guarda en su variable pk el id de la noticia para luego borrarla
    usuario.delete()
    messages.success(request, 'El usuario ha sido eliminado')
    return redirect('usuarios:listarUsuarios')

@login_required
def modificarUsuario(request, pk):
    usuario = get_object_or_404(Usuario, pk=pk)

    if request.method == 'POST':
        # Obtener los datos enviados por el formulario
        username = request.POST['username']
        email = request.POST['email']
        es_colaborador = 'es_colaborador' in request.POST

        try:
        # Actualizar el usuario con los datos modificados
            usuario.username = username
            usuario.email = email
            
            colaborador_group = Group.objects.get(name='colaborador')
            if es_colaborador:
                colaborador_group.user_set.add(usuario)
            else:
                colaborador_group.user_set.remove(usuario)
            
            usuario.save()

            # Redireccionar a la lista de usuarios o a otra página de tu elección
            return redirect('usuarios:listarUsuarios')
        except IntegrityError:
            # Si se produce una excepción de integridad debido a que el nombre de usuario ya existe, mostrar un mensaje de error.
            mensajeError = "El nombre de usuario ya está en uso. Por favor, elige otro nombre."
            context = {'usuario': usuario, 'es_colaborador': usuario.groups.filter(name='colaborador').exists(), 'mensajeError': mensajeError}
            return render(request, 'usuarios/modificar.html', context)

    # Si la petición es GET, mostrar el formulario con los datos actuales del usuario
    context = {'usuario': usuario, 'es_colaborador': usuario.groups.filter(name='colaborador').exists()}
    return render(request, 'usuarios/modificar.html', context)

repositorio/raiz/templates/usuarios/reestablecerPassword/password_reset_complete.html
<!-- no se esta ocupando, estoy usando usuarios/cambiarPassword/password_success -->

<h1>Contraseña restablecida</h1>
<p>Tu contraseña ha sido restablecida exitosamente. Ahora puedes iniciar sesión con tu nueva contraseña.</p>

repositorio/raiz/templates/usuarios/reestablecerPassword/password_reset_confirm.html
<!-- registration/password_reset_confirm.html -->

{% extends 'baseLogin.html' %}
{% load static %}

{% block contenido %}
<head>
  <link rel="stylesheet" href="{% static 'css/recuperarPassword.css' %}">
</head>

<div class="container-fluid">
  <div class="col-md-6">
    <h1 class="mb-4">Restablecer contraseña</h1>
    {% if validlink %}
      <form method="post">
        {% csrf_token %}
        <div class="form-group">
          <label for="{{ form.new_password1.id_for_label }}"><b>Nueva contraseña:</b></label>
          {{ form.new_password1 }}
        </div>
        <div class="form-group">
          <label for="{{ form.new_password2.id_for_label }}"><b>Confirmar nueva contraseña:</b></label>
          {{ form.new_password2 }}
        </div>
        {% if form.errors %}
          <p>Ha ocurrido un error al intentar recuperar la contraseña:</p>
          <ul>
          {% for field, errors in form.errors.items %}
            {% for error in errors %}
              <li>{{ field }}: {{ error }}</li>
            {% endfor %}
          {% endfor %}
        </ul>
      {% endif %}
        <button type="submit" class="btn btn-dark submit-btn">Guardar</button>
      </form>
    {% else %}
      <p>El enlace de recuperación de contraseña ha expirado o es inválido. Por favor, solicita un nuevo enlace de recuperación.</p>
    {%endif %} 
  </div>
</div>
{% endblock contenido %}

repositorio/raiz/templates/usuarios/reestablecerPassword/password_reset_done.html
{% extends 'baseLogin.html' %}
{% load static %}

{% block contenido %}

<div class="container-fluid d-flex justify-content-center align-items-center vh-100">
  <div class="col-md-6">
    <div class="text-center">
      <h1>Correo de recuperación enviado</h1>
      <p>Hemos enviado un correo electrónico a la dirección proporcionada con instrucciones para restablecer tu contraseña.</p>
    </div>
  </div>
</div>

{% endblock contenido %}

repositorio/raiz/templates/usuarios/reestablecerPassword/password_reset_email.html
Asunto: Restablecimiento de contraseña para tu cuenta en ODS2030 Blog

Hola Estimado Usuario,

Recibimos una solicitud para restablecer la contraseña de tu cuenta en el blog de ODS2030. Si no has solicitado este cambio, puedes ignorar este correo electrónico.

Si deseas restablecer tu contraseña, por favor haz clic en el siguiente enlace o cópialo y pégalo en tu navegador:

{{ protocol}}://{{ domain }}{% url 'usuarios:password_reset_confirm' uidb64=uid token=token %}

Ten en cuenta que este enlace caducará en 4 horas por motivos de seguridad. Si no completas el proceso de restablecimiento dentro de ese período, deberás realizar una nueva solicitud.

Si tienes alguna pregunta o necesitas asistencia adicional, no dudes en contactar con nuestro equipo de soporte en ods2030blog@gmail.com.

¡Gracias por ser parte de la comunidad ODS2030!

Saludos cordiales,
El equipo de ODS2030 Blog

repositorio/raiz/templates/usuarios/reestablecerPassword/password_reset_form.html
{% extends 'baseLogin.html' %}
{% load static %}

{% block contenido %}
<head>
  <link rel="stylesheet" href="{% static 'css/recuperarPassword.css' %}">
</head>
<div class="container-fluid">
  <div class="col-md-6">
    <h1 class="mb-4">Recuperar contraseña</h1>
    <form method="post">
      {% csrf_token %}
      <div class="form-group">
        <label for="Email"><b>Ingrese su Email:</b></label>
        <input type="email" class="form-control form-control-black" id="Email" name="email" aria-describedby="emailHelp">
      </div>
      <button type="submit" class="btn btn-dark submit-btn">Enviar</button>
    </form>
  </div>
</div>
{% endblock contenido %}