repositorio/raiz/apps/noticias/urls.py
from django.urls import path
from . import views

app_name='noticias'

urlpatterns = [
    # #URL CRUD'S

    #create
    path('agregarNoticia/', views.agregarNoticia, name='agregarNoticia'),
    path('agregarComentario/<int:pk>/', views.agregarComentario, name='agregarComentario'),

    #read
    path('listarNoticias/', views.listarNoticias, name='listarNoticias'),
    path('buscarNoticias/', views.buscarNoticias, name='buscarNoticias'),
    path('mostrarNoticia/<int:pk>/', views.mostrarNoticia, name='mostrarNoticia'),

    # #update
    path('modificarNoticia/<int:pk>/', views.modificarNoticia.as_view(), name='modificarNoticia'),

    #delete
    path('eliminarNoticia/<int:pk>/', views.eliminarNoticia, name='eliminarNoticia'),
    path('eliminarComentario/<int:pk>', views.eliminarComentario, name='eliminarComentario'),

]

repositorio/raiz/apps/usuarios/urls.py
from django.urls import path, reverse_lazy
from . import views

from django.contrib.auth import views as auth

app_name= 'usuarios'


urlpatterns = [
    
    path('registrarse/',views.registrarse.as_view(), name='registrarse'),
    path('login/',auth.LoginView.as_view(template_name='usuarios/loguearse.html'),name='loguearse'), #en vez de pasarle una vista mia paso una de django
    path('logout/',auth.LogoutView.as_view(),name="logout"),
    path('listar/',views.listarUsuarios,name="listarUsuarios"),
    path('eliminar/<int:pk>',views.eliminarUsuario,name="eliminarUsuario"),    
    path('modificar/<int:pk>',views.modificarUsuario,name="modificarUsuario"),   
    
    #modificar Password
    path('password_change/', views.password_change.as_view(), name='password_change'),
    path('password_success/', views.password_success, name='password_success'),
    #recuperacion de Password
    path(
        'password_reset/',
        auth.PasswordResetView.as_view(
        template_name='usuarios/reestablecerPassword/password_reset_form.html',
        email_template_name='usuarios/reestablecerPassword/password_reset_email.html',
        success_url=reverse_lazy('usuarios:password_reset_done')),
        name='password_reset'),
    path(
        'password_reset_done/',
        auth.PasswordResetDoneView.as_view(
        template_name='usuarios/reestablecerPassword/password_reset_done.html'),
        name='password_reset_done'),

    path(
        'password_reset/<uidb64>/<token>',
        auth.PasswordResetConfirmView.as_view(
        template_name='usuarios/reestablecerPassword/password_reset_confirm.html',
        success_url=reverse_lazy('usuarios:password_reset_complete')),
        name='password_reset_confirm'),

    path('password_reset_complete/',
        views.CustomPasswordResetCompleteView.as_view(
        template_name='usuarios/reestablecerPassword/password_reset_complete.html'),
        name='password_reset_complete'),                                
]

repositorio/raiz/blog/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings


from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', views.Home, name = 'home'),
    path('contacto/', views.Contacto, name = 'contacto'),
    path('usuarios/',include('apps.usuarios.urls')),
    path('objetivos/p<int:numObjetivo>.html', views.pagObjetivo, name='pagObjetivo'),
    path('noticias/',include('apps.noticias.urls')),
    
    path('emailContacto/', views.emailContacto, name = 'emailContacto'),

    path('permisoDenegado/', views.permisoDenegado, name = 'permisoDenegado'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

repositorio/raiz/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es-ar">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ODS 2030</title>
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <script src="{% static 'js/script.js' %}" defer></script>


</head>
<body> 
    <!-- header base -->
    <header>

        <div class="container">

            <a  class="logo" href="{%url 'home'%}">ODS 2030</a>
            <nav>
                <!-- Navbar Search-->
                <form action="{% url 'noticias:buscarNoticias' %}" method="post" class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
                    {% csrf_token %}
                    <div class="input-group">
                        <input class="form-control" type="text" placeholder="Buscar " id="buscar" name="buscar" aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                        <button class="btn btn-dark" id="btnNavbarSearch" type="submit"><i class="fas fa-search"></i></button>
                    </div>
                </form>
                
                {% if user.is_authenticated%}
                    <div class="menu2" data-dropdown>
                        <a class="usuarioBoton" data-dropdown-button>Noticias <i class="fas fa-caret-down"></i></a>
                        <div class="menuNoticias opciones">
                                <div class="">
                                    
                                  
                                    <a href="{%url 'noticias:listarNoticias' %}" class="configuracion">Ver</a>
                                    <a href="{%url 'noticias:agregarNoticia'%}" class="agregar">Agregar</a>
                                </div>
                        </div>
                    </div>
                    <a href="{%url 'contacto' %}">Contacto</a>
                    <div class="menu2" data-dropdown>
                            <a class="usuarioBoton" data-dropdown-button><i class="fas fa-user fa-fw"></i>{{user.username}} <i class="fas fa-caret-down"></i></a>
                            <div class="menuUsuario opciones">
                                    <div class="">
                                        {% if user.is_staff %}
                                            <a href="{%url 'usuarios:listarUsuarios'%}" class="usuarios">Usuarios</a>
                                        {%endif%}
                                        <a href="{%url 'usuarios:modificarUsuario' user.pk %}" class="configuracion">Cuenta</a>
                                        <a href="{%url 'usuarios:logout'%}" class="cerrarSesion">Cerrar sesión</a>
                                    </div>
                            </div>
                    </div>
                    
                {% endif %}
                {% if not user.is_authenticated%}
                    <a href="{%url 'noticias:listarNoticias'%}">Noticias</a>
                    <a href="{%url 'contacto' %}">Contacto</a>
                    <a href="{%url 'usuarios:loguearse'%}">Login</a>
                {% endif %}
            </nav> 

        </div>

   </header> 

   <div style="margin-bottom: 2rem;">
    {%block contenido%}

    {%endblock contenido%}
  </div>

  <!-- footer base -->
    <footer>

        <div class="pie">

            <div class="rectangulo">

                <div class="logo">
                    <img src="{% static 'img/base/pie-logo.jpg' %}" alt="Logo pie de página">

                </div>

                <div class="redes">
                    <span class="fb"><i class="fa-brands fa-facebook"></i></span>
                    <span class="twt"><i class="fa-brands fa-twitter"></i></span>
                    <span class="ig"><i class="fa-brands fa-instagram"></i></span>
                    <span class="li"><i class="fa-brands fa-linkedin"></i></span>
                    <span class="yt"><i class="fa-brands fa-youtube"></i></span>
                </div>

            </div>

        </div>

        <hr>

        <div class="section">
            <div class="title-container">
                <h6>Inicio</h6>
                <a href="link-17objetivos">Objetivos</a>
                <a href="link-enlaces-de-interes">Enlaces de Interés</a>
                <a href="link-suscribete">Suscripción</a>
                <a href="link-registro">Registrarte</a>
                <a href="link-login">Login</a>
            </div>

            <div class="title-container">
                <h6>Acerca de la República Argentina</h6>
                <a href="https://www.argentina.gob.ar/pais">Nuestro País</a>
                <a href="https://www.argentina.gob.ar/normativa">Leyes Argentinas</a>
                <a href="https://www.argentina.gob.ar/organismos">Organismos</a>
                <a href="https://www.argentina.gob.ar/jefatura/mapa-del-estado">Organismos</a>
            </div>

            <div class="title-container">
                <h6>Acerca de Argentina.gob.ar</h6>
                <a href="https://www.argentina.gob.ar/terminos-y-condiciones">Términos y condiciones</a>
                <a href="https://www.argentina.gob.ar/sugerencias">Sugerencias</a>
            </div>
            
        </div>

            <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.15);">
              <a class="text-reset fw-bold" href="{%url 'home'%}">ODS 2030</a> - © {{ year }} Informatorio
            </div>
    </footer>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="https://kit.fontawesome.com/94500f7625.js" crossorigin="anonymous"></script>
</body>
</html>

repositorio/raiz/templates/baseLogin.html
{% load static %}

<!DOCTYPE html> 
<html lang="es-ar">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ODS 2030</title>
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="{% static 'js/script.js' %}" defer></script>
    <script src="{% static 'js/scriptsBlog.js' %}" defer></script>
</head>
<body>
    <!-- header base -->
    <header>

        <div class="container">

            <a  class="logo" href="{%url 'home'%}">ODS 2030</a>
            <nav>
                <a href="{%url 'noticias:listarNoticias'%}">Noticias</a>
                <a href="{%url 'contacto' %}">Contacto</a>
                {% if user.is_authenticated%}
                    <div class="menu2" data-dropdown>
                        <a class="usuarioBoton" data-dropdown-button><i class="fas fa-user fa-fw"></i>{{user.username}} <i class="fas fa-caret-down"></i></a>
                        <div class="menuUsuario opciones">
                                <div class="">
                                    {% if user.is_staff %}
                                        <a href="{%url 'usuarios:listarUsuarios'%}" class="usuarios">Usuarios</a>
                                    {%endif%}
                                    <a href="{%url 'usuarios:password_change'%}" class="configuracion">Cuenta</a>
                                    <a href="{%url 'usuarios:logout'%}" class="cerrarSesion">Cerrar sesión</a>
                                </div>
                        </div>
                    </div>
                    
                {% endif %}
                {% if not user.is_authenticated%}
                    <a href="{%url 'usuarios:loguearse'%}">Login</a>
                {% endif %}
            </nav> 

        </div>

   </header> 

   <div style="margin-bottom: 2rem;">
    {% block contenido %}

    {% endblock contenido%}
   </div>
 
  
  <!-- footer base -->
    <!-- <footer class="fix-bottom" id="footer">

         Copyright 
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.15);">
     
        <a class="text-reset fw-bold" href="{%url 'home'%}">ODS 2030</a> - © {{ year }} Informatorio 

    </footer> -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="https://kit.fontawesome.com/94500f7625.js" crossorigin="anonymous"></script>
</body>
</html>

repositorio/raiz/templates/contacto.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}

<head>
  <link rel="stylesheet" href="{% static 'css/contacto.css' %}">
 
</head>
<!-- Contenido principal -->
<div style="margin-top: 60px;">
  <div class="container mt-5">
    <div class="row">
      <!-- Sobre nosotros -->
      <div class="col-md-6" style="border-right: 2px solid #000000;">
        <h2>Sobre nosotros</h2>
        <p>Somos un grupo apasionado de personas que estamos participando en el curso "Informatorio". Nuestro objetivo es aprender y contribuir de manera significativa al mundo que nos rodea. Como parte de nuestro proyecto final, hemos creado este sitio tipo blog dedicado a los Objetivos de Desarrollo Sostenible (ODS) 2030.</p>
        <p>Agradecemos tu visita a nuestro sitio y esperamos que encuentres información relevante y motivación para unirte a esta causa. Juntos, podemos contribuir al logro de los Objetivos de Desarrollo Sostenible y construir un futuro más sostenible y próspero para todos.</p>
      </div>
      <!-- Formulario de contacto -->
      <div class="col-md-6">
        <h2>Contacto</h2>
        <form>
          <div class="form-group">
            <label for="nombre">Nombre:</label>
            <input type="text" class="form-control" id="nombre" placeholder="Ingresa tu nombre" required>
          </div>
          <div class="form-group">
            <label for="email">Correo electrónico:</label>
            <input type="email" class="form-control" id="email" placeholder="Ingresa tu correo electrónico" required>
          </div>
          <div class="form-group">
            <label for="asunto">Asunto:</label>
            <input type="text" class="form-control" id="asunto" placeholder="Ingresa el asunto de tu mensaje" required>
          </div>
          <div class="form-group">
            <label for="mensaje">Mensaje:</label>
            <textarea class="form-control" id="mensaje" rows="5" placeholder="Escribe tu mensaje aquí" required></textarea>
          </div>
          <button type="submit" class="btn btn-dark">Enviar</button>
        </form>
      </div>
    </div>
    <hr>
    <!-- Mapa -->
    <div class="row mt-4">
      <div class="col-md-12 map-container">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3540.2638206554584!2d-58.98130792654952!3d-27.461044876324568!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94450ce8b2457993%3A0xb6cc63aac9bf8073!2sInformatorio!5e0!3m2!1ses-419!2sar!4v1690263979929!5m2!1ses-419!2sar" width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
      </div>
    </div>
  </div>
</div>
<!-- Enlace a Bootstrap JS y dependencias de jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.0.9/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

{% endblock contenido %}

repositorio/raiz/templates/home.html
{%extends 'base.html'%}
{%load static %}
{%block contenido%}

<section id="somos-ods">      

    <div class="container">

        <div class="img-container"></div>

        <h2>Los 17 objetivos de <span class="color-17objetivos">ODS 2030</span></h2>
        <p>Clickea sobre cualquiera de los objetivos de tu Interés!</p>
    </div>
</section>


<section id="los-link">
    
    <div class="carta-17objetivos">
        <div class="los17">
            {% for i in objetivos %}
                <a href="{% url 'pagObjetivo' numObjetivo=i %}">
                    <img src="{% static 'img/objetivos/' %}{{ i }}ods.jpg" alt="Objetivo {{ i }}">
                </a>
            {% endfor %}
        </div>

    </div>
    
</section>


<section id="enlaces-de-interes">

    <div class="container">
        <h2>Enlaces de Interés</h2>

        <div class="programas">

            <div class="carta">
                <h3>¡Únete a nosotros!</h3>
                <p>Explora cómo tus acciones diarias pueden marcar 
                la diferencia y cómo puedes colaborar.</p>
                <form action ="link-a-la-pag"><button class="botonHome">Más Info</button>
                </form>
            </div>

            <div class="carta">
                <h3>Ultimas Noticias</h3>
                <p>Conoce las historias inspiradoras 
                de cambio y transformación que están ocurriendo en nuestra 
                querida provincia.</p>
                <form action ="link-a-la-pag"><button class="botonHome">Más Info</button>
                </form>
            </div>

            <div class="carta">
                <h3>Recursos y Herramientas</h3>
                <p>Resumen recursos y herramientas para una mayor comprensión
                de esta organización, con datos y páginas web donde puedes informarte
                más</p>
                <form action ="link-a-la-pag"><button class="botonHome">Más Info</button>
                </form>
            </div>

        </div>

    </div>

</section>

<section id="hero">
    <h1>Suscríbete a nuestro portal <br>y ayúdanos a ayudar</h1>
    <a href="{%url 'usuarios:registrarse'%}"></a><button class="botonHome">SUSCRIBETE</button>
</section>

{%endblock contenido%}